name: dm-proj
channels: [conda-forge]
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyterlab
  - seaborn
  - xgboost
  - pip
  - pip:
      - nbstripout
      - jupytext
